### ISSUE TITLE
upgrade to truffle 4

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-contracts#20]
https://github.com/trufflesuite/truffle/releases

**Comment by aeftimia** [comment]
Unknown contracts are running out of gas in Truffle 4. This seems to be a common problem due to Truffle 4 [turning off an optimizer](https://github.com/trufflesuite/truffle/releases/tag/v4.0.0) that was on by default in the prior release. This [can be reverted manually](http://truffleframework.com/docs/advanced/configuration#solidity-compiler-configuration). Since there were security concerns regarding the optimizer, we may want to split up the logic in larger contracts. As we improve the architecture of these contracts down the road, this problem may resolve itself, so it's probably best to just turn the optimizer back on in the short run and make splitting up or simplifying contract logic a goal for future refactoring.

**Comment by aeftimia** [comment]
It seems reverting the optimizer settings failed to resolve the contracts exceeding gas limits. We may have to refactor contracts before we can upgrade.

**Comment by jellegerbrandy** [comment]
the solution was to add a gas limit in truffle.js
